### ISSUE TITLE
Kravspec

### ISSUE THREAD

**Issue by JonasLR** [Distribuerede-Systemer-2017/STFU#4]

**Comment by Pewtro** [comment]
Gennemgå til øvelsestimen d. 10/10, derefter luk.

**Comment by Pewtro** [comment]
Skal færdiggøres og pushes live senest onsdag d. 12/10 kl. 12

**Comment by Pewtro** [comment]
Ligger herind nu: https://github.com/Distribuerede-Systemer-2017/STFU/blob/master/KRAVSPEC.md 

Er de færdige?
