### ISSUE TITLE
Use cases + beskrivelser

### ISSUE THREAD

**Issue by lucasweje** [Distribuerede-Systemer-2017/STFU#6]
Use case 1 - Albert
Use case 2 - Theresia
Use case 3 - Lucas
4 - Iben
5 - Emil
6 - Jonas
7 - Ingvild
8 - Frederik
9 - 
10 - Frederik Jeppesen
11 - Laust
12 - Lucas 
13 - Täck
14 - Morten

**Comment by Pewtro** [comment]
Skal være færdige inden øvelse d. 10 / 10.

**Comment by Pewtro** [comment]
Jeg har skrevet dem ind her: https://github.com/Distribuerede-Systemer-2017/STFU/blob/master/USE_CASES.md

I må meget gerne lige gå dem igennem og se om alting passer/er som det skal, og opdater hvor nødvendigt.
